---
- name: import pulp keys
  command: >
    oc replace
    --namespace={{ pulp_secret_namespace }}
    --force=true
    --filename={{ pulp_secret_remote_dir }}/openshift-pulpsecret.yml
  environment: "{{ pulp_secret_environment }}"
  notify: allow service account

- name: allow service account
  command: >
    oc secrets
    add serviceaccount/{{ pulp_secret_service_account }} secrets/{{ pulp_secret_name }}
    --for=mount
    --namespace={{ pulp_secret_namespace }}
  environment: "{{ pulp_secret_environment }}"

- name: delete resource file
  file: path={{ pulp_secret_remote_dir }}/openshift-pulpsecret.yml state=absent
